version: 1
services:
  mongodb:
    image: ./mongodb
    environment:
      - MONGO_INITDB_DATABASE: bisous
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: root$123
    ports:
      - 27017-27019:27017:27019
    volumes:
      - ./mongo-volume:/data/mongo