version: '3'
services:
  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_DATABASE: "bisous"
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./mongo-volume:/data/db